"""
Model Catalog - Downloadable local models for stable-diffusion.cpp.

This file is generated/maintained from the stable-diffusion.cpp docs:
https://github.com/leejet/stable-diffusion.cpp

Run `python scripts/update_model_catalog.py` to refresh the catalog.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ModelArtifact:
    """
    A single downloadable artifact from Hugging Face.

    Use either:
      - `filename` for an exact file, or
      - `patterns` to auto-select a file from the repo at download time.
    """

    repo: str
    filename: str | None = None
    patterns: list[str] = field(default_factory=list)
    description: str = ""


@dataclass(frozen=True)
class CatalogModel:
    """A curated model entry shown in the UI."""

    name: str
    description: str
    architecture: str  # "sd15", "sdxl", "sd2", "sd-turbo", etc.
    artifacts: list[ModelArtifact]

    # If True, and the primary artifact is a GGUF file, also download companion
    # component files (VAE/CLIP/T5/etc.) from the same repo when present.
    include_components: bool = True


# BEGIN AUTOGENERATED (do not edit by hand)
MODEL_CATALOG: list[CatalogModel] = [
    CatalogModel(
        name="Stable Diffusion 1.5 (safetensors)",
        description="Baseline SD 1.5 model (single file, ungated mirror for easy download)",
        architecture="sd15",
        artifacts=[
            ModelArtifact(
                repo="second-state/stable-diffusion-v1-5-GGUF",
                filename="v1-5-pruned-emaonly.safetensors",
            )
        ],
        include_components=False,
    ),
    CatalogModel(
        name="Stable Diffusion 1.5 (GGUF Q4_0)",
        description="Quantized SD 1.5 GGUF (smallest). Downloads companion components if available in repo.",
        architecture="sd15",
        artifacts=[
            ModelArtifact(
                repo="second-state/stable-diffusion-v1-5-GGUF",
                filename="stable-diffusion-v1-5-pruned-emaonly-Q4_0.gguf",
            )
        ],
        include_components=True,
    ),
    CatalogModel(
        name="Stable Diffusion XL Base 1.0 (+ VAE fix)",
        description="SDXL base model plus recommended VAE fix from stable-diffusion.cpp docs",
        architecture="sdxl",
        artifacts=[
            ModelArtifact(
                repo="stabilityai/stable-diffusion-xl-base-1.0",
                filename="sd_xl_base_1.0.safetensors",
            ),
            ModelArtifact(
                repo="madebyollin/sdxl-vae-fp16-fix",
                filename="sdxl_vae-fp16-fix.safetensors",
                description="VAE fix (pass as --vae / vae_path)",
            ),
        ],
        include_components=False,
    ),
    CatalogModel(
        name="SSD-1B (SDXL distilled, A1111 safetensors)",
        description="Smaller distilled SDXL-style model from stable-diffusion.cpp docs (out-of-the-box)",
        architecture="sdxl",
        artifacts=[
            ModelArtifact(
                repo="segmind/SSD-1B",
                filename="SSD-1B-A1111.safetensors",
            )
        ],
        include_components=False,
    ),
    CatalogModel(
        name="SSD-1B (fp8 safetensors)",
        description="SSD-1B fp8 variant (may require newer GPUs/drivers; out-of-the-box per docs)",
        architecture="sdxl",
        artifacts=[
            ModelArtifact(
                repo="hassenhamdi/SSD-1B-fp8_e4m3fn",
                filename="SSD-1B_fp8_e4m3fn.safetensors",
            )
        ],
        include_components=False,
    ),
    CatalogModel(
        name="SD Turbo (auto-select)",
        description="Turbo SD model; downloads a matching safetensors file from the repo",
        architecture="sd-turbo",
        artifacts=[
            ModelArtifact(
                repo="stabilityai/sd-turbo",
                patterns=["*.safetensors"],
            )
        ],
        include_components=False,
    ),
    CatalogModel(
        name="SDXL Turbo (auto-select)",
        description="Turbo SDXL model; downloads a matching safetensors file from the repo",
        architecture="sdxl-turbo",
        artifacts=[
            ModelArtifact(
                repo="stabilityai/sdxl-turbo",
                patterns=["*.safetensors"],
            )
        ],
        include_components=False,
    ),
]
# END AUTOGENERATED
